name: Setup docker
description: Sets up docker with buildx for use in other actions.

inputs:
  buildx_version:
    description: "The buildx version to use."
    default: v0.11.2

runs:
  using: composite
  steps:
    - name: setup docker context for buildx
      id: buildx-context
      shell: bash
      run: docker context create builders

    - name: setup docker buildx
      uses: docker/setup-buildx-action@v3.0.0
      with:
        endpoint: builders
        version: ${{ inputs.buildx_version }}
        
    - uses: imjasonh/setup-crane@00c9e93efa4e1138c9a7a5c594acd6c75a2fbf0c # pin@v0.3
      with:
        version: v0.15.2