name: Setup akidosec safe chain
description: Sets up akidosec safe chain.

runs:
  using: composite
  steps:
    - name: Install safechain
      shell: bash
      run: curl -fsSL https://github.com/AikidoSec/safe-chain/releases/latest/download/install-safe-chain.sh | sh -s -- --ci

    - name: Export shim envs
      shell: bash 
      run: |
        echo "/home/runner/.safe-chain/shims" >> $GITHUB_PATH
