name: Send Custom Metrics
description: Sends custom metrics to an endpoint

inputs:
  METRICS_ENDPOINT_URL:
    description: The metrics endpoint URL
    required: true
  BEARER_TOKEN:
    description: The authorization token for the endpoint
    required: true
  data:
    description: The metric data to send
    required: true

runs:
  using: composite
  steps:
    - name: Validate Metrics Data
      shell: bash
      env:
        METRICS_DATA: ${{ inputs.data }}
      run: |
        if ! [[ "$METRICS_DATA" =~ ^[a-zA-Z_:][a-zA-Z0-9_:]*\{?.*\}? [0-9]+ ]]; then
          echo "The provided metric data does not match the expected Prometheus format."
          exit 1
        fi
        echo "Metric data is valid."

    - name: Send Metric
      shell: bash
      run: |
        curl -H "Authorization: Bearer ${{ inputs.BEARER_TOKEN }}" \
             -X POST "${{ inputs.METRICS_ENDPOINT_URL }}" \
             -d '${{ inputs.data }}'
