name: Google Artifact Registry Login
description: Authenticate to Google Cloud and login to Google Artifact Registry.

inputs:
  GCP_WORKLOAD_IDENTITY_PROVIDER:
    description: "The GCP Workload Identity Provider to use for authentication."
    required: true
  GCP_SERVICE_ACCOUNT_EMAIL:
    description: "The GCP Service Account Email to use for authentication."
    required: true
  create_credentials_file:
    description: "Whether to create a credentials file."
    default: "false"

runs:
  using: composite
  steps:
    - id: auth
      name: "Authenticate to Google Cloud"
      uses: google-github-actions/auth@v1.1.1
      with:
        create_credentials_file: ${{ inputs.create_credentials_file == 'true' }}
        token_format: "access_token"
        workload_identity_provider: ${{ inputs.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ inputs.GCP_SERVICE_ACCOUNT_EMAIL }}

    - name: Login to Google Artifact Registry
      uses: docker/login-action@v3.0.0
      with:
        registry: us-docker.pkg.dev # use multi-region GAR
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}
