name: 'Check for Dependabot alerts & send them to Slack'

on:
  workflow_call:
    secrets:
      slack-webhook:
        required: true
        description: 'Slack Webhook'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.DEPENDABOT_SLACK_APPID }}
          private-key: ${{ secrets.DEPENDABOT_SLACK_SECRET }}

      # Latest version available at: https://github.com/kunalnagarco/action-cve/releases
      - uses: kunalnagarco/action-cve@v1.14.1
        with:
          token: ${{ steps.app-token.outputs.token }}
          slack_webhook: ${{ secrets.slack-webhook }}
          count: 10