name: test-actions

on:
  push:

permissions:
  contents: read
  id-token: write #required for GCP Workload Identity federation which we use to login into Google Artifact Registry

jobs:
  run-docker-buildx-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./docker-buildx-setup
  run-gar-auth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./gar-auth
