name: "Test debug"

on:
  push:

permissions:
  contents: read
  id-token: write #required for GCP Workload Identity federation which we use to login into Google Artifact Registry

jobs:
  run-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3

      - uses: aptos-labs/aptos-core/.github/actions/rust-setup@3860bf2c8010908887408d8443f01ba05cfedc4d
