name: "Test rust-setup"

on:
  push:

jobs:
  run-rust-setup-default:
    runs-on: high-perf-docker
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3
        with:
          path: actions

      - uses: ./actions/rust-setup
        with:
          GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}
          CHECKOUT_REPOSITORY: aptos-labs/aptos-core

      # Because we have to checkout the actions in the first step, and then check out a rust repo (aptos-core), the actions directory will get overwritten
      # We need to check it out again for the Post Run actions/checkout to succeed
      # This is a special case for tests written in this repo
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3
        with:
          path: actions

  run-rust-setup-aptos-core:
    runs-on: high-perf-docker
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3
        with:
          path: actions

      - uses: ./actions/rust-setup
        with:
          GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}
          CHECKOUT_REPOSITORY: aptos-labs/aptos-core
          REPOSITORY_SPECIFIC_SETUP: scripts/dev_setup.sh -b -r

      # Because we have to checkout the actions in the first step, and then check out a rust repo (aptos-core), the actions directory will get overwritten
      # We need to check it out again for the Post Run actions/checkout to succeed
      # This is a special case for tests written in this repo
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3
        with:
          path: actions
